KEY_MAP = {
    "W": "earpiece_down",
    "A": "earpiece_up",
    "J": "cute_row_1",
    "H": "cute_row_2",
    "G": "cute_row_3",
    "F": "cute_row_4",
    "D": "cute_row_5",
    "E": "direction_up",
    "T": "direction_down",
    "Y": "direction_left",
    "R": "direction_right",
    "U": "direction_center",
    "X": "color_1",
    "C": "color_2",
    "V": "color_3",
    "B": "color_4",
    "N": "color_5",
    "K": "color_6",
    "O": "symbol_sun",
    "L": "symbol_moon",
    "S": "symbol_cloud",
    "Z": "symbol_wheel",
    "I": "symbol_stop"
}
